version: "3.3"
services:
  server:
    container_name: server
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgress
      DB_LOGIN: postgress
      DB_PASSWORD: postgress
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  data-volume:
